import '../styles/globals.css';
import type { AppProps } from 'next/app';
import {
  AppShell,
  ColorScheme,
  ColorSchemeProvider,
  MantineProvider,
} from '@mantine/core';
import { useState } from 'react';
import Head from 'next/head';
import { Header } from '../components';

function MyApp({ Component, pageProps }: AppProps) {
  const [colorScheme, setColorScheme] =
    useState<ColorScheme>('dark');
  const toggleColorScheme = (value?: ColorScheme) =>
    setColorScheme(value || (colorScheme === 'dark' ? 'light' : 'dark'));

  return (
    <ColorSchemeProvider
      colorScheme={colorScheme}
      toggleColorScheme={toggleColorScheme}
    >
      <MantineProvider
        theme={{
          colorScheme: colorScheme,
          colors: {
            'primary': ['#1DB954', '#1ED760'],
            'backgroundColor': ['#ffffff', '#191414'],
          }
        }}
      >
        <Head>
          <title> Spotify song data visualizer </title>
          <meta name='description' content='Generated by create next app' />
          <link rel='icon' href='/favicon.ico' />
        </Head>
        <AppShell
          padding={'md'}
          header={<Header />}
          styles={(theme) => ({
            main: {
              backgroundColor:
                theme.colorScheme === 'dark'
                  ? theme.colors.backgroundColor[1]
                  : theme.colors.backgroundColor[0],
            },
          })}
        >
          <Component {...pageProps} />
        </AppShell>
      </MantineProvider>
    </ColorSchemeProvider>
  );
}

export default MyApp;
